/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CreateKeyDialog: typeof import('./components/CreateKeyDialog.vue')['default']
    HashKeyDetailDialog: typeof import('./components/HashKeyDetailDialog.vue')['default']
    Menu: typeof import('./components/Menu.vue')['default']
    RedisKeysExplorer: typeof import('./components/RedisKeysExplorer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StringKeyDetailDialog: typeof import('./components/StringKeyDetailDialog.vue')['default']
    TtlPicker: typeof import('./components/TtlPicker.vue')['default']
  }
}
