using Microsoft.AspNetCore.Mvc;

namespace Roman.RedisManager.Web.Controllers
{
    [ApiController]
    [Route("/error")]
    [ApiExplorerSettings(IgnoreApi = true)]
    public class ErrorController : ControllerBase
    {
        // This endpoint is invoked by the exception handler middleware and
        // returns a ProblemDetails response generated by MVC.
        public IActionResult HandleError()
            => Problem();
    }
}
